spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tarefasdb
    username: root
    password: senha
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/tarefasdb

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource-h2:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
